import { randomUUID, createHash } from 'node:crypto';
import { Pool, type PoolConfig } from 'pg';
import type { QueryResultRow } from 'pg';

export interface PostgresDatabaseConfig {
  connectionString: string;
  ssl: boolean;
  demoUserEmail: string;
  demoUserPassword: string;
  demoUserDisplayName: string;
}

export class PostgresDatabase {
  private readonly pool: Pool;
  private initialized = false;

  constructor(private readonly config: PostgresDatabaseConfig) {
    const poolConfig: PoolConfig = {
      connectionString: config.connectionString,
      max: 5,
    };

    if (config.ssl) {
      poolConfig.ssl = { rejectUnauthorized: false };
    }

    this.pool = new Pool(poolConfig);
  }

  async initialize() {
    if (this.initialized) return;

    await this.pool.query('SELECT 1');
    await this.pool.query(`
      CREATE TABLE IF NOT EXISTS api_users (
        id TEXT PRIMARY KEY,
        email TEXT NOT NULL UNIQUE,
        display_name TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        provider_ids TEXT[] NOT NULL DEFAULT '{}'
      );

      CREATE TABLE IF NOT EXISTS ftp_profiles (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        owner_id TEXT NOT NULL,
        name TEXT NOT NULL,
        host TEXT NOT NULL,
        port INTEGER NOT NULL DEFAULT 21,
        username TEXT NOT NULL,
        password TEXT NOT NULL,
        use_ftps BOOLEAN NOT NULL DEFAULT FALSE,
        passive_mode BOOLEAN NOT NULL DEFAULT TRUE
      );

      CREATE TABLE IF NOT EXISTS sync_records (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        owner_id TEXT NOT NULL,
        profile_id INTEGER NOT NULL REFERENCES ftp_profiles(id) ON DELETE CASCADE,
        date TIMESTAMPTZ NOT NULL,
        local_path TEXT NOT NULL,
        remote_path TEXT NOT NULL,
        mode TEXT NOT NULL,
        files_transferred INTEGER NOT NULL DEFAULT 0,
        files_skipped INTEGER NOT NULL DEFAULT 0,
        error_message TEXT
      );
    `);

    await this.pool.query(
      'CREATE INDEX IF NOT EXISTS idx_ftp_profiles_owner_id ON ftp_profiles(owner_id)',
    );
    await this.pool.query(
      'CREATE INDEX IF NOT EXISTS idx_sync_records_owner_id ON sync_records(owner_id)',
    );

    await this.seedDemoUser();
    this.initialized = true;
  }

  private async seedDemoUser() {
    const passwordHash = createHash('sha256')
      .update(this.config.demoUserPassword)
      .digest('hex');

    await this.pool.query(
      `
      INSERT INTO api_users (id, email, display_name, password_hash, provider_ids)
      VALUES ($1, $2, $3, $4, $5)
      ON CONFLICT (email)
      DO UPDATE SET
        display_name = EXCLUDED.display_name,
        password_hash = EXCLUDED.password_hash,
        provider_ids = EXCLUDED.provider_ids
      `,
      [
        randomUUID(),
        this.config.demoUserEmail.toLowerCase(),
        this.config.demoUserDisplayName,
        passwordHash,
        ['password'],
      ],
    );
  }

  query<T extends QueryResultRow = QueryResultRow>(
    text: string,
    params?: unknown[],
  ) {
    return this.pool.query<T>(text, params);
  }
}
